apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-solr
  labels:
    app: {{ .Release.Name }}-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-solr
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-solr
    spec:
      volumes:
        - name: {{ .Release.Name }}-solr-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-solr-pvc
      containers:
        - name: solr
          image: solr:9.8.1
          volumeMounts:
            - mountPath: "/data"
              name: {{ .Release.Name }}-solr-storage
          resources:
            requests:
              memory: 2Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 0.5
          env:
            - name: SOLR_HOME
              value: /data
            - name: JAVA_OPTS
              value: --add-modules jdk.incubator.vector
          ports:
            - containerPort: 8983

